### ISSUE TITLE
Recursion error with pyvoro

### ISSUE THREAD

**Issue by josealgeciras** [joel-simon/evo_floorplans#1]
Hi there,

I'm extremely new in Python and I am struggling to run your 'Evo-floorplans' project on 'Python 3.6.8: Anaconda custom (64-bit)' on macOS. I have installed all the requirements you pointed at for this package. I took it I also needed SWIG and/or Cython to make Pyvoro work properly, but it is simply not going well.

Do you have an idea to lead me in the right direction?

this is what I get when trying to run the test.py file:

$ python test.py
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from floor_plans.floorplan import FloorPlan
  File "/Users/josealgecirasrodriguez/Code/evo_floorplans-master/floor_plans/floorplan.py", line 11, in <module>
    from floor_plans.voronoi import voronoi_cells
  File "/Users/josealgecirasrodriguez/Code/evo_floorplans-master/floor_plans/voronoi.py", line 6, in <module>
    import pyvoro
  File "/Users/josealgecirasrodriguez/anaconda3/lib/python3.6/site-packages/pyvoro/__init__.py", line 1, in <module>
    import voroplusplus
  File "voroplusplus.pyx", line 36, in init pyvoro.voroplusplus (pyvoro/voroplusplus.cpp:2696)
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 166, in _get_module_lock
RecursionError: maximum recursion depth exceeded while calling a Python object

thanks in advance!

**Comment by joel-simon** [comment]
Hello :)
Sorry to hear you are having issues. TBH this code was not cleaned up or made easy to run... Are you able to run pyvoro on its own ok?

**Comment by josealgeciras** [comment]
Hi Joel
thanks for your comment!

I made it run (so proud...) in Python 2.7. I also tested pyvoro on its own and it goes well. now the issue is different, maybe I should edit the title.

When I run the code it appears something is missing. A setting within the config file, something to import, I don't really know, but my guess after tracking the errors is that no genome list is filled with data. Any thoughts?

thank you again!!!

After attempting to run the script i get this messages on the console (errors at the end):

> $ python main.py
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> /Users/josealgecirasrodriguez/anaconda3/envs/py27/lib/python2.7/site-packages/matplotlib/__init__.py:962: UserWarning: Duplicate key in file "/Users/josealgecirasrodriguez/.matplotlib/matplotlibrc", line #2
>   (fname, cnt))
> 
>  ****** Running generation 0 ****** 
> 
> missing cells: 33 
> 3missing cells: 19 28 32 33 
> 3E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'2missing cells: 33 39 46 47 
> 32missing cells: 5 21 25 47 
> 3E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'2E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'missing cells: 1 6 15 43 
> 3missing cells: 21 
> 3missing cells: 16 18 26 
> 3missing cells: 13 
> 3missing cells: 2 
> 32missing cells: 15 16 24 38 
> 3E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'missing cells: 9 14 32 47 51 
> 3missing cells: 1 9 45 49 
> 3E'FloorPlan' object has no attribute 'edges_iter'missing cells: 21 43 
> 3missing cells: 24 46 
> 3missing cells: 15 42 47 
> 3E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'missing cells: 21 23 
> 3missing cells: 15 
> 3E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'missing cells: 14 
> 322missing cells: 10 
> 3E'FloorPlan' object has no attribute 'edges_iter'2E'FloorPlan' object has no attribute 'edges_iter'E'FloorPlan' object has no attribute 'edges_iter'2missing cells: 6 12 16 17 19 25 26 32 38 39 40 46 49 50 51 
> 3E'FloorPlan' object has no attribute 'edges_iter'missing cells: 8 44 
> 3missing cells: 33 
> Traceback (most recent call last):
>   File "main.py", line 270, in <module>
>     pop.run(evaluate_all, generations)
>   File "/Users/josealgecirasrodriguez/Code/evo_floorplans-master/floor_plans/population.py", line 172, in run
>     fitness_function(population)
>   File "main.py", line 244, in evaluate_all
>     draw_genome(best)
>   File "main.py", line 234, in draw_genome
>     floorplan = FloorPlan.from_genome(genome)
>   File "/Users/josealgecirasrodriguez/Code/evo_floorplans-master/floor_plans/floorplan.py", line 241, in from_genome
>     cells, debug_data = voronoi_cells(pos, genome.node_genes, a) # Room walls by voronoi tesselation.
>   File "/Users/josealgecirasrodriguez/Code/evo_floorplans-master/floor_plans/voronoi.py", line 112, in voronoi_cells
>     raise e
> pyvoro.voroplusplus.VoronoiPlusPlusError: number of cells found was not equal to the number of particles.

**Comment by joel-simon** [comment]
Hey, I think the netowrkx lib graph object (https://networkx.github.io/) uses edges_iter in python3, so since you switched to python2 it probably needs replacing "edges_iter" with "edges"

Joel
