### ISSUE TITLE
Better usability modeling via recursive modelings (GRAINS)

### ISSUE THREAD

**Issue by NewAlexandria** [joel-simon/evo_floorplans#2]
When I saw this work, [I thought of this recent paper on auto-modeling useful spaces](https://www.cse.iitb.ac.in/~sidch/docs/tog2019_grains.pdf). The floorplans from evo_floorplans are great for traffic, but have limited use and build-ability.  Balancing-in those factors would be interesting.

**Comment by joel-simon** [comment]
Hey, thanks for the link, looks very interesting!
