### ISSUE TITLE
Proposal for a more usable codebase...

### ISSUE THREAD

**Issue by tswallen** [joel-simon/evo_floorplans#3]
Hey!

The paper accompanying this repo is nothing short of amazing to me! I haven't run this repo, but upon reading it, it seems a lot is hard-coded into this and it wasn't very readable. Is there a version of this code that works better with more plans?

**Comment by joel-simon** [comment]
Hi, glad you like it. Unfortunately, the code is messy. That's why I held off releasing it, was quickly thrown together research code. 
I if I revisit the project in the future it will be much cleaner :)
